name: Tests

on:
    push:
        branches: [ main, prototype, ci-test ]
    pull_request:
        branches: [ main, prototype ]

jobs:
    Test-Linux:
        runs-on: ubuntu-latest
        timeout-minutes: 90

        strategy:
            fail-fast: false
            matrix:
                name: [
                    "USD-22.05-py37",
                    "USD-22.05-py27",
                ]

                include:
                  -   name: "USD-22.05-py37"
                      usd-tag: "v22.05"
                      python: "3.7"
                  -   name: "USD-22.05-py27"
                      usd-tag: "v22.05"
                      python: "2.7"

        steps:
            -   name: Set up Python ${{ matrix.python }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   uses: actions/checkout@v3
            -   name: Buid
                run: |
                    mkdir build && cd build
                    cmake -DPython_FIND_STRATEGY=LOCATION -DPython_ROOT_DIR="$pythonLocation" ..
                    make
            -   name: Run tests
                run: |
                    cd build
                    CTEST_OUTPUT_ON_FAILURE=1 make test
